server:
  port: 8080

spring:
  application:
    name: banking-transaction-management
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    com.example.banking: INFO

fraud:
  amount-threshold: 100000
  tx-count-threshold: 5
  tx-window-minutes: 10
  blacklisted-account-ids: [999001, 999002, 999003]
