spring.datasource.url=${postgresql://banking_db_pm4f_user:y4jL3sz31AHysdEAZKoMMXqM0Gy5sNxh@dpg-d6n7bpkr85hc73df7uhg-a/banking_db_pm4f}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
