### 1) Create Customer
POST http://localhost:8080/customers
Content-Type: application/json

{
  "name": "Anand Kumar",
  "email": "anand@example.com",
  "phone": "+919876543210"
}

### 2) Create Sender Account
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "customerId": 1,
  "accountType": "SAVINGS",
  "initialBalance": 200000
}

### 3) Create Receiver Account
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "customerId": 1,
  "accountType": "CURRENT",
  "initialBalance": 10000
}

### 4) Get Account Details
GET http://localhost:8080/accounts/1

### 5) Check Balance
GET http://localhost:8080/accounts/1/balance

### 6) Deposit
POST http://localhost:8080/transactions/deposit
Content-Type: application/json

{
  "accountId": 1,
  "amount": 5000
}

### 7) Withdraw
POST http://localhost:8080/transactions/withdraw
Content-Type: application/json

{
  "accountId": 1,
  "amount": 2000
}

### 8) Transfer (High-value fraud rule example)
POST http://localhost:8080/transactions/transfer
Content-Type: application/json

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 120000
}

### 9) Transaction History
GET http://localhost:8080/transactions/history/1

### 10) Fraud Alerts
GET http://localhost:8080/fraud-alerts
